Declare miner to depend on bitcoind
Otherwise it risks to start too early
$ dc logs miner
miner-1  | Starting miner server
miner-1  | thread 'tokio-runtime-worker' panicked at src/main.rs:69:78:
miner-1  | called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(SocketError(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))
miner-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
miner-1  | miner exited